### ISSUE TITLE
Exception while sending message over Kafka

### ISSUE THREAD

**Issue by mkanchwala** [chriscasano/SetTopBox#1]
I am trying to setup this one but still facing problem.

```
java -cp SetTopBox.jar com.hortonworks.settopbox.MessageSender /root/SetTopBox/DemoData.properties
Loading properties...
Input File = /root/SetTopBox/input_test.txt
Broker List = <MyIP>:6667
Millisecond Delay = 250
Required Acks = 1
Message Topic = settopbox
Serializer Class = kafka.serializer.StringEncoder
log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
log4j:WARN Please initialize the log4j system properly.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Processing input file...
{"id":"1001","channel_s":"10","gmt_offset_s":"-00000","src_tl":"1419740100000","market_s":"New York City","program_s":"News","device_id_s":"50276","zip_code_s":"10025","network_s":"NBC","state_s":"NY","latlong_p":"40.7127,-74.0059","uptimedays_i":"81","event_dt":"2016-01-22T17:58:34Z"}
Error...
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
        at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
        at kafka.producer.Producer.send(Producer.scala:76)
        at kafka.javaapi.producer.Producer.send(Producer.scala:33)
        at com.hortonworks.settopbox.MessageSender.sendEvents(MessageSender.java:84)
        at com.hortonworks.settopbox.MessageSender.<init>(MessageSender.java:48)
        at com.hortonworks.settopbox.MessageSender.main(MessageSender.java:112)
Failed to send messages after 3 tries.
Message sending complete.


```

**Comment by chriscasano** [comment]
Make sure the Kafka port is forwarded on the VM.  If you're using Virtual Box, choose your VM -> Settings -> Network -> Port Forwarding.  My Kafka broker port was 6667.
